/* automatically generated by rust-bindgen 0.59.2 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Compositor {
    _unused: [u8; 0],
}
pub type Window = ::std::os::raw::c_ulong;
pub type GLXPixmap = ::std::os::raw::c_ulong;
extern "C" {
    pub fn create_compositor(display: *const ::std::os::raw::c_char) -> *mut Compositor;
}
extern "C" {
    pub fn init_compositor(compositor: *mut Compositor) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn destroy_compositor(compositor: *mut Compositor);
}
extern "C" {
    pub fn free_compositor(compositor: *mut Compositor);
}
extern "C" {
    pub fn get_root_window(compositor: *mut Compositor) -> Window;
}
extern "C" {
    pub fn get_composite_window(compositor: *mut Compositor) -> Window;
}
extern "C" {
    pub fn get_window_width(compositor: *mut Compositor, window: Window) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn get_window_height(compositor: *mut Compositor, window: Window) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn get_window_depth(compositor: *mut Compositor, window: Window) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn get_window_x(compositor: *mut Compositor, window: Window) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn get_window_y(compositor: *mut Compositor, window: Window) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn swap_buffers(compositor: *mut Compositor);
}
extern "C" {
    pub fn get_windows_recursive(
        compositor: *mut Compositor,
        parent: Window,
        windows: *mut *mut Window,
        nwindows: *mut ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn get_all_windows(
        compositor: *mut Compositor,
        windows_ret: *mut *mut Window,
        nwindows_ret: *mut ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn free_windows(windows: *mut Window);
}
extern "C" {
    pub fn create_glx_pixmap(compositor: *mut Compositor, window: Window) -> GLXPixmap;
}
extern "C" {
    pub fn destroy_glx_pixmap(compositor: *mut Compositor, glx_pixmap: GLXPixmap);
}
extern "C" {
    pub fn glx_bind_window_texture(compositor: *mut Compositor, glx_pixmap: GLXPixmap);
}
extern "C" {
    pub fn glx_unbind_window_texture(compositor: *mut Compositor, glx_pixmap: GLXPixmap);
}
